"""Configuration management for BadgerDrop"""

from badgerdrop.config.constants import (
    BORDER_RADIUS_LARGE,
    BORDER_RADIUS_MEDIUM,
    BORDER_RADIUS_SMALL,
    BORDER_RADIUS_XSMALL,
    COPY_CHUNK_SIZE,
    DEFAULT_AUTO_MAKE_EXECUTABLE,
    DEFAULT_CONFIG_DIR,
    DEFAULT_INSTALL_DIR,
    DEFAULT_PLAY_SOUND,
    DEFAULT_SHOW_NOTIFICATIONS,
    DEFAULT_SOUND_THEME,
    FONT_SIZE_ARROW,
    FONT_SIZE_SUBTITLE,
    FONT_SIZE_TITLE,
    FONT_SIZE_TOAST,
    ICON_SIZE_DEFAULT,
    PADDING_LARGE,
    PADDING_MEDIUM,
    PADDING_SMALL,
    PADDING_XLARGE,
    PERMISSION_EXECUTABLE,
    PERMISSION_FILE,
    PROCESS_TERMINATE_TIMEOUT,
    TRANSITION_FAST,
    TRANSITION_MEDIUM,
    TRANSITION_SLOW,
    UNSAFE_FILENAME_CHARS,
    WINDOW_DEFAULT_HEIGHT,
    WINDOW_DEFAULT_WIDTH,
)
from badgerdrop.config.paths import (
    get_applications_dir,
    get_config_dir,
    get_default_install_dir,
    get_icons_dir,
    get_installed_registry_file,
    get_local_share_dir,
    get_settings_file,
)
from badgerdrop.config.settings import SettingsManager

__all__ = [
    # Constants
    "WINDOW_DEFAULT_WIDTH",
    "WINDOW_DEFAULT_HEIGHT",
    "BORDER_RADIUS_LARGE",
    "BORDER_RADIUS_MEDIUM",
    "BORDER_RADIUS_SMALL",
    "BORDER_RADIUS_XSMALL",
    "PADDING_XLARGE",
    "PADDING_LARGE",
    "PADDING_MEDIUM",
    "PADDING_SMALL",
    "FONT_SIZE_TITLE",
    "FONT_SIZE_SUBTITLE",
    "FONT_SIZE_ARROW",
    "FONT_SIZE_TOAST",
    "TRANSITION_SLOW",
    "TRANSITION_MEDIUM",
    "TRANSITION_FAST",
    "PERMISSION_EXECUTABLE",
    "PERMISSION_FILE",
    "COPY_CHUNK_SIZE",
    "ICON_SIZE_DEFAULT",
    "UNSAFE_FILENAME_CHARS",
    "DEFAULT_INSTALL_DIR",
    "DEFAULT_CONFIG_DIR",
    "PROCESS_TERMINATE_TIMEOUT",
    "DEFAULT_PLAY_SOUND",
    "DEFAULT_SOUND_THEME",
    "DEFAULT_AUTO_MAKE_EXECUTABLE",
    "DEFAULT_SHOW_NOTIFICATIONS",
    # Paths
    "get_config_dir",
    "get_settings_file",
    "get_installed_registry_file",
    "get_local_share_dir",
    "get_applications_dir",
    "get_icons_dir",
    "get_default_install_dir",
    # Settings
    "SettingsManager",
]
